<?php

$citation = array(
	array('author' => 'Carlos Drummond de Andrade' , 'msg' => 'Ser feliz sem motivo é a mais autêntica forma de felicidade.'), 
	array('author' => 'Carlos Drummond de Andrade' , 'msg' => 'Perder tempo em aprender coisas que não interessam, priva-nos de descobrir coisas interessantes.'), 
	array('author' => 'Fernando Pessoa' , 'msg' => 'Tudo vale a pena quando a alma não é pequena.'), 
	array('author' => 'Fernando Pessoa' , 'msg' => 'Há tanta suavidade em nada dizer e tudo entender...'), 
	array('author' => 'John Ruskin' , 'msg' => 'Somente quando encontramos o amor, é que descobrimos o que nos faltava na vida.'), 
	array('author' => 'Pitágoras' , 'msg' => 'Com organização e tempo, acha-se o segredo de fazer tudo e bem feito.'), 
	array('author' => 'Santo Agostinho' , 'msg' => 'Ninguém faz bem o que faz contra a vontade, mesmo que seja bom o que faz.'), 
	array('author' => 'Santo Agostinho' , 'msg' => 'A angústia de ter perdido não supera a alegria de ter um dia possuído.'), 
	array('author' => 'Santo Agostinho' , 'msg' => 'Ter fé é assinar uma folha em branco e deixar que Deus nela escreva o que quiser.'), 
	array('author' => 'Nelson Mandela' , 'msg' => 'No meu país, é preciso primeiro ir para a cadeia para depois ser presidente.'), 
	array('author' => 'Nelson Mandela' , 'msg' => 'A grandeza da vida não consiste em não cair nunca, mas em nos levantarmos cada vez que caímos.'), 
	array('author' => 'Nelson Mandela' , 'msg' => 'Lutar contra a pobreza não é um assunto de caridade, mas de justiça.'), 
	array('author' => 'Nelson Mandela' , 'msg' => 'Ninguém nasce odiando o outro pela cor de sua pele, ou por sua origem, ou sua religião. Para odiar as pessoas precisam aprender, e se elas aprendem a odiar, podem ser ensinadas a amar.'), 
	array('author' => 'Barack Obama' , 'msg' => 'A mudança não acontecerá se nós esperarmos por outra pessoa ou se esperarmos por algum outro momento. Nós somos as pessoas pelas quais esperávamos. Nós somos a mudança que buscamos.'), 
	array('author' => 'Barack Obama' , 'msg' => 'Podemos compreender que haverá guerras, mas ainda assim lutar pela paz.'), 
	array('author' => 'Barack Obama' , 'msg' => 'Não viramos as costas nem vacilamos. Com os olhos fixos no horizonte e com a graça de Deus sobre nós, levamos adiante o grande dom da liberdade e o entregamos em segurança às futuras gerações.'), 
	array('author' => 'Barack Obama' , 'msg' => 'Livre-se dos bajuladores. Mantenha perto de você pessoas que te avisem quando você erra.'),
	array('author' => 'C. S. Lewis' , 'msg' => 'Cada vez que você faz uma opção está transformando sua essência em alguma coisa um pouco diferente do que era antes.'),
	array('author' => 'C. S. Lewis' , 'msg' => 'Quando se trata de conhecer a Deus, toda a iniciativa depende dEle. Se Ele não se quiser revelar, nada do que façamos nos permitirá encontrá-lo.'),
	array('author' => 'C. S. Lewis' , 'msg' => 'Pensava que nós seguíamos caminhos já feitos, mas parece que não os há. O nosso ir faz o caminho.'),
	array('author' => 'C. S. Lewis' , 'msg' => 'Deus não quer algo de nós. Ele simplesmente nos quer.'),
	array('author' => 'C. S. Lewis' , 'msg' => 'Tudo que é eterno está eternamente acima do tempo.'),
	array('author' => 'C. S. Lewis' , 'msg' => 'Seja estranho. Seja aleatório. Seja quem você é. Porque você nunca sabe quem amaria a pessoa que você esconde.'),
	array('author' => 'Martin Luther King' , 'msg' => 'O que me preocupa não é o grito dos maus. É o silêncio dos bons.'),
	array('author' => 'Martin Luther King' , 'msg' => 'Se um homem não descobriu nada pelo qual morreria, não está pronto para viver.'),
	array('author' => 'Martin Luther King' , 'msg' => 'No final, não nos lembraremos das palavras dos nossos inimigos, mas do silêncio dos nossos amigos.'),
	array('author' => 'Martin Luther King' , 'msg' => 'Suba o primeiro degrau com fé. Não é necessário que você veja toda a escada. Apenas dê o primeiro passo.'),
	array('author' => 'Martin Luther King' , 'msg' => 'Se não puder voar, corra. Se não puder correr, ande. Se não puder andar, rasteje, mas continue em frente de qualquer jeito.'),
	array('author' => 'Martin Luther King' , 'msg' => 'O perdão é um catalisador que cria a ambiência necessária para uma nova partida, para um reinício.'),
	array('author' => 'Martin Luther King' , 'msg' => 'A injustiça num lugar qualquer é uma ameaça à justiça em todo o lugar.'),
	array('author' => 'Jesus Cristo' , 'msg' => 'De que serve ao homem conquistar o mundo inteiro se perder a alma?'),
	array('author' => 'Jesus Cristo' , 'msg' => 'Vós sois o sal da terra; e se o sal for insípido, com que se há de salgar? Para nada mais presta senão para se lançar fora, e ser pisado pelos homens.'),
	array('author' => 'Jesus Cristo' , 'msg' => 'Mas seja, porém, o vosso falar: Sim, sim; Não, não; porque o que passa disto é de procedência maligna.'),
	array('author' => 'Jesus Cristo' , 'msg' => 'Não vos inquieteis, pois, pelo dia de amanhã, porque o dia de amanhã cuidará de si mesmo. Basta a cada dia o seu mal.'),
	array('author' => 'Jesus Cristo' , 'msg' => 'Não julgueis, para que não sejais julgados. Porque com o juízo com que julgardes sereis julgados, e com a medida com que tiverdes medido vos hão de medir a vós.'),
	array('author' => 'Jesus Cristo' , 'msg' => 'Se tu podes crer, tudo é possível ao que crê.

Marcos 9:23.'),
	array('author' => 'Jesus Cristo' , 'msg' => 'Eu sou o caminho, e a verdade e a vida; ninguém vem ao Pai, senão por mim.'),
	array('author' => 'Jesus Cristo' , 'msg' => 'Eu sou a luz do mundo; quem me segue não andará em trevas, mas terá a luz da vida.'),
	array('author' => 'Jesus Cristo' , 'msg' => 'Se alguém quer vir após mim, negue-se a si mesmo, e tome cada dia a sua cruz, e siga-me.'),
	array('author' => 'Jesus Cristo' , 'msg' => 'As coisas que são impossíveis aos homens são possíveis a Deus.'),
	array('author' => 'Mahatma Gandhi' , 'msg' => 'Um não dito com convicção é melhor e mais importante que um sim dito meramente para agradar, ou, pior ainda, para evitar complicações.'),
	array('author' => 'Mahatma Gandhi' , 'msg' => 'Assim como uma gota de veneno compromete um balde inteiro, também a mentira, por menor que seja, estraga toda a nossa vida.'),
	array('author' => 'Mahatma Gandhi' , 'msg' => 'O fraco jamais perdoa: o perdão é uma das características do forte.'),
	array('author' => 'Mahatma Gandhi' , 'msg' => 'A alegria está na luta, na tentativa, no sofrimento envolvido e não na vitória propriamente dita.'),
	array('author' => 'Mahatma Gandhi' , 'msg' => 'Cada dia a natureza produz o suficiente para nossa carência. Se cada um tomasse o que lhe fosse necessário, não havia pobreza no mundo e ninguém morreria de fome.'),
	array('author' => 'Mahatma Gandhi' , 'msg' => 'Você nunca sabe que resultados virão da sua ação. Mas se você não fizer nada, não existirão resultados.'),
	array('author' => 'Mario Sergio Cortella' , 'msg' => 'É necessário cuidar da ética para não anestesiarmos a nossa consciência e começarmos a achar que tudo é normal.'),
	array('author' => 'Mario Sergio Cortella' , 'msg' => 'A tragédia não é quando um homem morre. A tragédia é o que morre dentro de um homem quando ele está vivo.'),
	array('author' => 'Mario Sergio Cortella' , 'msg' => 'Coragem é preparo e não mera disposição eufórica.'),
	array('author' => 'Mario Sergio Cortella' , 'msg' => 'A tristeza do rio é não poder parar. Se você pode, aproveite.'),
	array('author' => 'Mario Sergio Cortella' , 'msg' => 'Agir conforme aquilo que se fala, alinhar discurso e prática, além de ser uma postura ética, é um sinal de autenticidade.'),
	array('author' => 'Mario Sergio Cortella' , 'msg' => 'Mudar é complicado, mas se acomodar é perecer.'),
	array('author' => 'Mario Sergio Cortella' , 'msg' => 'Gente não nasce pronta e vai se gastando; gente nasce não-pronta e vai se fazendo.'),
	array('author' => 'Mario Sergio Cortella' , 'msg' => 'O impossível não é um fato: é uma opinião.'),
	array('author' => 'Mario Sergio Cortella' , 'msg' => 'A motivação é uma porta que se abre por dentro.'),
	);

?>
